"""Default settings for cybergraph-game demos and small simulations."""

NUM_NODES = 12
NUM_EDGES = 18
NUM_ENTRY_POINTS = 2
GRAPH_SEED = 1

RANDOM_SEED = 7
NUM_TIME_STEPS = 12

ATTACK_SUCCESS_PROBABILITY = 0.6
DEFENDER_ACTION_PROBABILITY = 0.35
DEFENDER_ADD_NODE_PROBABILITY = 0.4
ADDED_NODE_EDGE_COUNT = 2

SECURITY_LEVEL_MIN = 1
SECURITY_LEVEL_MAX = 3
DEFAULT_SECURITY_LEVEL = 1
ADDED_NODE_SECURITY_LEVEL = 3
